# Site settings
title: Dr Susanna Waern
description: ""
baseurl: ""
url: http://drsusannawaern.co.uk
name: Dr Susanna Waern
phone: 07881 958 424
email: dr.susanna.waern@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
